#!/usr/bin/env python3
"""pixelize: turn AI "fake pixel art" into true pixel art for Castle Quest.

Commands (run from the repo root):
  palette RAW [--size 640x360] [--colors 48]
      Extract the game palette from the approved background and write
      assets/palette.png + js/palette.js. Run once; the palette is then locked.
  bg RAW OUT [--size 640x360] [--preview]
      Background: snap to the pixel grid and the palette.
  sprite OUT RAW [RAW ...] --cell WxH [--scale auto|N] [--each] [--hole] [--tol 90] [--preview]
      Cut-out sprite sheet: one frame per RAW, left to right.

--preview also writes a 4x nearest-neighbor copy to art/preview/ for viewing.
"""
import argparse
from collections import Counter, deque
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PALETTE_PNG = ROOT / 'assets' / 'palette.png'
PALETTE_JS = ROOT / 'js' / 'palette.js'
PREVIEW_DIR = ROOT / 'art' / 'preview'
MAGENTA = (255, 0, 255)
CYAN = (0, 255, 255)


def parse_size(s):
    w, h = s.lower().split('x')
    return int(w), int(h)


def dist2(a, b):
    return (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2


def pixels(img):
    """All pixel values, flattened (Pillow 12 renamed getdata)."""
    get = getattr(img, 'get_flattened_data', None)
    return list(get() if get else img.getdata())


def downsample(img, size):
    """Resample to exactly `size`. Each output pixel is the dominant color in
    the middle 60% of its source cell (AI pixel edges wobble, so they're
    skipped). Colors vote in coarse buckets so noise can't split the vote;
    the winner is the mean of its bucket."""
    img = img.convert('RGB')
    sw, sh = img.size
    w, h = size
    src = img.load()
    out = Image.new('RGB', (w, h))
    dst = out.load()
    for y in range(h):
        y0, y1 = y * sh / h, (y + 1) * sh / h
        iy = (y1 - y0) * 0.2
        ya = int(y0 + iy)
        ys = range(ya, max(ya + 1, int(y1 - iy)))
        for x in range(w):
            x0, x1 = x * sw / w, (x + 1) * sw / w
            ix = (x1 - x0) * 0.2
            xa = int(x0 + ix)
            xs = range(xa, max(xa + 1, int(x1 - ix)))
            votes = Counter()
            sums = {}
            for j in ys:
                for i in xs:
                    c = src[i, j]
                    k = (c[0] >> 4, c[1] >> 4, c[2] >> 4)
                    votes[k] += 1
                    s = sums.setdefault(k, [0, 0, 0])
                    s[0] += c[0]
                    s[1] += c[1]
                    s[2] += c[2]
            k, n = votes.most_common(1)[0]
            s = sums[k]
            dst[x, y] = (round(s[0] / n), round(s[1] / n), round(s[2] / n))
    return out


def extract_palette(img, n):
    """Median-cut the image down to at most n colors and return them."""
    q = img.convert('RGB').quantize(colors=n, method=Image.Quantize.MEDIANCUT)
    flat = q.getpalette()
    used = sorted(set(pixels(q)))
    return list(dict.fromkeys(tuple(flat[i * 3:i * 3 + 3]) for i in used))


def snap(img, palette):
    """Map every opaque pixel to its nearest palette color. Keeps alpha."""
    img = img.convert('RGBA')
    p = img.load()
    cache = {}
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = p[x, y]
            if a == 0:
                continue
            c = cache.get((r, g, b))
            if c is None:
                c = cache[(r, g, b)] = min(palette, key=lambda q: dist2(q, (r, g, b)))
            p[x, y] = (c[0], c[1], c[2], 255)
    return img


def write_palette(palette, png=None, js=None):
    png = Path(png or PALETTE_PNG)
    js = Path(js or PALETTE_JS)
    png.parent.mkdir(parents=True, exist_ok=True)
    im = Image.new('RGB', (len(palette), 1))
    im.putdata(palette)
    im.save(png)
    hexes = ', '.join("'#%02x%02x%02x'" % c for c in palette)
    js.write_text('/* Generated by tools/pixelize.py palette. Do not edit by hand. */\n'
                  f'Castle.PALETTE = [{hexes}];\n', encoding='utf-8')


def load_palette(path=None):
    return list(dict.fromkeys(pixels(Image.open(path or PALETTE_PNG).convert('RGB'))))


def require_palette():
    if not Path(PALETTE_PNG).exists():
        raise SystemExit('No palette yet: run "python tools/pixelize.py palette art/raw/kitchen-bg.png" first.')
    return load_palette(PALETTE_PNG)


def save(img, out, preview):
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out)
    print(f'wrote {out} ({img.width}x{img.height})')
    if preview:
        PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
        pv = PREVIEW_DIR / out.name
        img.resize((img.width * 4, img.height * 4), Image.NEAREST).save(pv)
        print(f'preview {pv}')


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)
    p = sub.add_parser('palette')
    p.add_argument('raw')
    p.add_argument('--size', default='640x360')
    p.add_argument('--colors', type=int, default=48)
    b = sub.add_parser('bg')
    b.add_argument('raw')
    b.add_argument('out')
    b.add_argument('--size', default='640x360')
    b.add_argument('--preview', action='store_true')
    a = ap.parse_args(argv)

    if a.cmd == 'palette':
        pal = extract_palette(downsample(Image.open(a.raw), parse_size(a.size)), a.colors)
        write_palette(pal, PALETTE_PNG, PALETTE_JS)
        print(f'wrote {PALETTE_PNG} and {PALETTE_JS} ({len(pal)} colors)')
    elif a.cmd == 'bg':
        img = snap(downsample(Image.open(a.raw), parse_size(a.size)), require_palette())
        save(img.convert('RGB'), a.out, a.preview)


if __name__ == '__main__':
    main()
